app/entity/models.py
from slugify import slugify
from sqlalchemy import event

from app.database import db

class Entity(db.Model):
    __tablename__ = 'entity'

    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(1000), nullable=False, unique=True)
    slug = db.Column(db.String(1000))
    content = db.Column(db.String(5000))

    comments = db.relationship('Comment', backref='entity')

    def __str__(self):
        return self.name


@event.listens_for(Entity, 'before_insert')
def event_before_insert(mapper, connection, target):
    # Здесь будет очень важная бизнес логика
    # Или нет. На самом деле, старайтесь использовать сигналы только
    # тогда, когда других, более правильных вариантов не осталось.
    target.slug = slugify(target.name)


@event.listens_for(Entity, 'before_update')
def event_before_update(mapper, connection, target):
    target.slug = slugify(target.name)

app/entity/forms.py
from flask.ext.wtf import Form
from wtforms import (
    StringField,
    TextAreaField,
)
from wtforms.validators import DataRequired

class EntityCreateForm(Form):
    name = StringField(
        'Name',
        [
            DataRequired(message="This field is required")
        ],
        description="Name of the entity"
    )
    content = TextAreaField(
        'Content',
        [],
        description="Content of the entity",
    )

app/comment/controllers.py
from flask import (
    Blueprint,
    request,
    flash,
    abort,
    redirect,
    url_for,
    current_app,
)
from sqlalchemy.exc import SQLAlchemyError

from app.database import db
from .models import Comment
from .forms import CommentAddForm


module = Blueprint('comment', __name__, url_prefix='/comment')


def log_error(*args, **kwargs):
    current_app.logger.error(*args, **kwargs)


@module.route('/add/', methods=['POST'])
def add():
    form = CommentAddForm(request.form)
    try:
        if request.method == 'POST' and form.validate():
            comment = Comment(**form.data)
            db.session.add(comment)
            db.session.commit()
            flash('Comment was successful added!', 'success')
            return redirect(url_for('entity.view', id=comment.entity_id))
    except SQLAlchemyError as e:
        log_error('There was error while querying database', exc_info=e)
        db.session.rollback()
        flash('Uncaught exception while querying database', 'danger')
        abort(500)

app/entity/controllers.py
from flask import (
    Blueprint,
    render_template,
    request,
    flash,
    abort,
    redirect,
    url_for,
    current_app,
)
from sqlalchemy.exc import SQLAlchemyError
from sqlalchemy.orm import joinedload

from .models import Entity, db
from .forms import EntityCreateForm
from app.utils.db import sqlalchemy_orm_to_dict
from app.comment.forms import CommentAddForm
from app.comment.models import Comment

module = Blueprint('entity', __name__)

def log_error(*args, **kwargs):
    current_app.logger.error(*args, **kwargs)


@module.route('/', methods=['GET'])
@module.route('/page/<int:page>/', methods=['GET'])
def index(page=1):
    entities = None
    try:
        entities = Entity.query.paginate(page, 1, True)
    except SQLAlchemyError as e:
        log_error('Error while querying database', exc_info=e)
        flash('There was uncaught database query', 'danger')
        abort(500)
    return render_template('entity/index.html', object_list=entities)


@module.route('/<int:id>/view/', methods=['GET'])
def view(id):
    entity = None
    cmt_form = CommentAddForm(request.form)
    try:
        entity = db.session.\
            query(Entity).\
            filter(Entity.id == id).\
            options(joinedload(Entity.comments)).\
            first()
    except SQLAlchemyError as e:
        log_error('Error while querying database', exc_info=e)
        flash('There was error while querying database', 'danger')
        abort(500)
    return render_template('entity/view.html', object=entity, form=cmt_form)


@module.route('/create/', methods=['GET', 'POST'])
def create():
    form = EntityCreateForm(request.form)
    try:
        if request.method == 'POST' and form.validate():
            entity = Entity(**form.data)
            db.session.add(entity)
            db.session.flush()
            id = entity.id
            db.session.commit()
            flash('The entity was successfully added!', 'success')
            return redirect(url_for('entity.view', id=id))
    except SQLAlchemyError as e:
        log_error('There was error while querying database', exc_info=e)
        db.session.rollback()
        flash('There was error while querying database', 'error')
    return render_template('entity/create.html', form=form)


@module.route('/<int:id>/update/', methods=['GET', 'POST'])
def update(id):
    form = EntityCreateForm(request.form)
    entity = Entity.query.get_or_404(id)
    try:
        if request.method == 'POST' and form.validate_on_submit():
            for key, val in form.data.items():
                if hasattr(entity, key):
                    setattr(entity, key, val)
            db.session.commit()
            flash('Entity successful updated!', 'success')
            return redirect(url_for('entity.view', id=id))
        else:
            form = EntityCreateForm(**sqlalchemy_orm_to_dict(entity))
    except SQLAlchemyError as e:
        db.session.rollback()
        log_error('Uncaught exception while '
                  'querying database at entity.update', exc_info=e)
        flash('Uncaught error while querying database', 'danger')
        abort(500)
    return render_template('entity/update.html', form=form, id=id)


@module.route('/view/<int:id>/remove/', methods=['GET', 'POST'])
def remove(id):
    entity = None
    try:
        if request.method == 'POST':
            entity = Entity.query.filter_by(id=id).first_or_404()
            Comment.query.filter(Comment.entity_id == entity.id).delete()
            db.session.delete(entity)
            db.session.commit()
            flash('Entity was successful removed!', 'success')
            return redirect(url_for('entity.index'))
        else:
            entity = Entity.query.get_or_404(id)
    except SQLAlchemyError as e:
        db.session.rollback()
        log_error('Uncaught exception '
                  'while querying database at entity.remove', exc_info=e)
        flash('Uncaught exception while querying database', 'danger')
        abort(500)
    return render_template('entity/delete.html', object=entity)

app/templates/entity/create.html
{% extends 'base.html' %}

{% block meta_title %} Create a new entity {% endblock %}

{% block content %}

    {% include 'form-errors.html' %}
    {% import 'form-macros.html' as macros %}

    <div class="col-md-6">
        {% call macros.render_form(form, action_url=url_for("entity.create"), action_text="Create", btn_class="btn btn-primary") %}
            {{ macros.render_field(form.name, label_visible=True, placeholder="Name", type="text", show_help=True) }}
            {{ macros.render_field(form.content, label_visible=True, placeholder="Content", type="text", show_help=True) }}
        {% endcall %}
    </div>
{% endblock %}

app/templates/entity/delete.html
{% extends 'base.html' %}

{% block meta_title %} Confirm entity removing {% endblock %}

{% block content %}

    {% include "messages.html" %}

    {% if object %}
        <form class="form-horizontal" action="{{ url_for('entity.remove', id=object.id) }}" method="post">
            <div class="panel panel-info">
                <div class="panel-heading"><strong>Information</strong></div>

                <div class="panel-body">
                    <dl class="dl-horizontal">
                        <dt>ID:</dt>
                        <dd>{{ object.id }}</dd>

                        <dt>Name: </dt>
                        <dd>{{ object.name }}</dd>
                    </dl>
                </div>

                <div class="panel-footer">
                    <br/>
                    <div class="form-group">
                        <div class="col-xs-offset-0 col-xs-10">
                            <input type="submit" value="Remove" class="btn btn-danger btn-group-sm" />
                        </div>
                    </div>
                </div>
            </div>

        </form>
    {% endif %}
{% endblock %}

app/templates/entity/index.html
{% extends "base.html" %}

{% block meta_title %} List of all entities {% endblock %}

{% block content %}

    {% if object_list.items %}
        {% for entity in object_list.items %}
            <div class="blog-post">
                <h2 class="blog-post-title"><a href="{{ url_for('entity.view', id=entity.id) }}">{{ entity.name }}</a></h2>
                <div class="blog-post-content">
                    {{ entity.content }}
                </div>
            </div><!-- /.blog-post -->
        {% endfor %}
    {% else %}
        <div class="alert alert-info">There is no posts added yet. Wanna <a href="{{ url_for('entity.create') }}">add some</a>?</div>
    {% endif %}

{% endblock %}

{% block pagination %}
    {% import "pagination.html" as pagination_macros %}
    {{ pagination_macros.render_pagination(object_list, 'entity.index') }}
{% endblock pagination %}

app/templates/entity/update.html
{% extends 'base.html' %}

{% block meta_title %} Update entity #{{ id }} {% endblock meta_title %}

{% block content %}

    {% include 'form-errors.html' %}
    {% import 'form-macros.html' as macros %}

    <div class="col-md-6">
        {% call macros.render_form(form, action_url=url_for("entity.update", id=id), action_text="Update", btn_class="btn btn-warning") %}
            {{ macros.render_field(form.name, label_visible=True, placeholder="Name of the entity", type="text", show_help=True) }}
            {{ macros.render_field(form.content, label_visible=True, placeholder="Entity content", type="text", show_help=True) }}
        {% endcall %}
    </div>

{% endblock %}

app/templates/entity/view.html
{% extends 'base.html' %}

{% block content %}
    <div class="blog-post">
        <h2 class="blog-post-title">{{ object.name }}</h2>
        <div class="blog-post-content">
            {{ object.content }}
        </div>
        <hr/>
        <div class="blog-post-meta">
            <a href="{{ url_for('entity.update', id=object.id) }}" class="btn btn-warning">Modify</a>
            <a href="{{ url_for('entity.remove', id=object.id) }}" class="btn btn-danger">Remove</a>
        </div>
    </div><!-- /.blog-post -->

    <h3>Comments!</h3>
    {% if object.comments|length > 0 %}
        {% for comment in object.comments %}
            {% if comment.email %}
                <strong><a href="mailto:{{ comment.email }}">{{ comment.name }}</a></strong>
            {% else %}
                <strong>{{ commment.name }}</strong>
            {% endif %}
            <br/>
            {{ comment.content }}
            <hr/>
        {% endfor %}
    {% else %}
        <div class="alert alert-info">There is no comment yet. Be the first!</div>
    {% endif %}

    <h3>Submit your comment!</h3>
    {% include 'form-errors.html' %}
    {% import 'form-macros.html' as macros %}
    {% call macros.render_form(form, action_url=url_for("comment.add"), action_text="Comment!", btn_class="btn btn-primary") %}
        {{ macros.render_field(form.name, label_visible=True, placeholder="Name", type="text", show_help=True) }}
        {{ macros.render_field(form.email, label_visible=True, placeholder="Name", type="text", show_help=True) }}
        {{ macros.render_field(form.content, label_visible=True, placeholder="Content", type="text", show_help=True) }}
        {{ macros.render_field(form.entity_id, label_visible=False, type="hidden", show_help=False, value=object.id) }}
    {% endcall %}

{% endblock content %}